---
defaults: &defaults
  docker:
    - image: gcr.io/planet-4-151612/circleci-base:latest
  working_directory: /home/circleci/app

version: 2

jobs:
  deploy-dev:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: planet4-production
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: activate-gcloud-account.sh
      - run: docker-login.sh
      - run: make -C deploy checkout-master
      - run: make -C deploy build
      - run: make -C deploy docker-push
      - run: make -C deploy dev

  deploy-tag:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: planet4-production
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: activate-gcloud-account.sh
      - run: docker-login.sh
      - run: make -C deploy checkout-tag
      - run: make -C deploy build
      - run: make -C deploy docker-push
      - run: make -C deploy prod

workflows:
  version: 2
  dev:
    jobs:
      - deploy-dev:
          context: org-global
          filters:
            branches:
              only: master
  tag:
    jobs:
      - deploy-tag:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
